// SPEC-09 §2 — 8 action types with defined timeouts
export enum HITLActionType {
  APPROVE_LEAD_LIST = "APPROVE_LEAD_LIST",
  SEND_EXTERNAL_MESSAGE = "SEND_EXTERNAL_MESSAGE",
  SEND_PROPOSAL = "SEND_PROPOSAL",
  APPROVE_MOCKUP = "APPROVE_MOCKUP",
  APPROVE_STAGING = "APPROVE_STAGING",
  DEPLOY_PRODUCTION = "DEPLOY_PRODUCTION",
  APPROVE_BRIEFING = "APPROVE_BRIEFING",
  SEND_DELIVERY = "SEND_DELIVERY",
}
