name: Feature Request
description: Suggest an idea for Hefesto AI
labels: ["enhancement"]
body:
  - type: textarea
    id: feature
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see.
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like.
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or features you've considered.
  - type: checkboxes
    id: checks
    attributes:
      label: Impact
      options:
        - label: This is a core feature for Hefesto architecture.
        - label: This improves Developer Experience (DX).
