INSERT INTO skill_catalog (name, slug, description, skill_type, config_template, service_types, persona_hints, is_builtin) VALUES
('Caveman Workflow', 'caveman-workflow', 'Git workflow e deploy: Conventional Commits, feature branches, worktrees, CI/CD.', 'prompt_template',
 '{"systemPromptAddition":"Ao gerenciar código:\n- Siga Conventional Commits (feat/fix/chore/test/docs)\n- Use feature branches, nunca commite direto na main\n- Squash merge ao mesclar PRs\n- Use worktrees para tasks paralelas\n- Valide CI antes de qualquer merge\n- Documente WHY, nunca WHAT"}',
 ARRAY['SITE_CREATION','FULL_DIGITAL'], ARRAY['BUILDER','QA'], true),
('ECC Code Quality', 'ecc-code-quality', 'Clean Architecture, TDD, TypeScript strict, OWASP. Sem any, sem console.log.', 'prompt_template',
 '{"systemPromptAddition":"Ao escrever código:\n- TypeScript strict, nunca use any\n- Clean Architecture: domain→application→infrastructure→http\n- TDD: RED→GREEN→REFACTOR\n- Sem console.log, use logger com correlationId\n- Zod em todas as boundaries\n- OWASP Top 10: sem SQL injection, XSS, SSRF"}',
 ARRAY['SITE_CREATION','FULL_DIGITAL'], ARRAY['BUILDER','QA'], true),
('UI/UX Design Pro', 'ui-ux-design-pro', 'Design mobile-first, WCAG 2.2, shadcn/ui, Tailwind 4, hierarquia visual.', 'prompt_template',
 '{"systemPromptAddition":"Ao criar interfaces:\n- Mobile-first, depois desktop\n- Contraste WCAG AA (4.5:1 texto, 3:1 UI)\n- Sistema de design: variáveis CSS, escala tipográfica\n- Componentes acessíveis: aria-labels, keyboard nav\n- Performance: WebP, lazy loading, CLS < 0.1\n- CTA visualmente proeminente"}',
 ARRAY['SITE_CREATION','SOCIAL_MEDIA','FULL_DIGITAL'], ARRAY['BUILDER','BRIEFING'], true),
('Social Media Strategy', 'social-media-strategy', 'Calendário editorial, formatos por plataforma, hashtags, engajamento, KPIs.', 'prompt_template',
 '{"systemPromptAddition":"Ao criar estratégia social:\n- Mapeie público-alvo antes de qualquer conteúdo\n- Instagram: 3-5 posts/semana, Reels 3x mais alcance\n- Calendário: 40% educativo, 30% entretenimento, 20% vendas, 10% UGC\n- 5-10 hashtags (popular + nicho)\n- KPI: engajamento > 3%"}',
 ARRAY['SOCIAL_MEDIA','FULL_DIGITAL'], ARRAY['CLOSER','BUILDER'], true),
('Traffic Manager', 'traffic-manager', 'Google Ads, Meta Ads, UTM tracking, otimização de conversão, ROI, retargeting.', 'prompt_template',
 '{"systemPromptAddition":"Ao planejar tráfego:\n- Google Ads: Search > Display para conversão\n- Meta Ads: lookalike 1-2%\n- UTM em todos os links\n- Budget mínimo R$30/dia para dados em 7 dias\n- ROAS alvo >= 3x\n- Teste A/B antes de escalar"}',
 ARRAY['TRAFFIC_MANAGEMENT','FULL_DIGITAL'], ARRAY['CLOSER','BUILDER'], true),
('SEO Optimizer', 'seo-optimizer', 'Meta tags, schema markup, Core Web Vitals, sitemap, Google Business Profile.', 'prompt_template',
 '{"systemPromptAddition":"Ao otimizar SEO:\n- Title: 50-60 chars, keyword no início\n- Meta description: 120-160 chars, unique\n- Schema: LocalBusiness, Product, FAQ\n- Core Web Vitals: LCP < 2.5s, CLS < 0.1\n- Google Business Profile: NAP consistente\n- H1 único por página"}',
 ARRAY['SITE_CREATION','FULL_DIGITAL'], ARRAY['BUILDER','QA'], true),
('HUASHU Analytics', 'huashu-analytics', 'KPIs, funil de conversão, cohort analysis, relatórios automatizados, anomaly detection.', 'prompt_template',
 '{"systemPromptAddition":"Ao analisar dados:\n- Defina KPIs antes de implementar tracking\n- Funil: Impressões→Cliques→Sessões→Leads→Conversões\n- Relatório semanal: GAP vs meta + 3 insights acionáveis\n- Alerta se métrica cair > 20% vs semana anterior\n- Atribuição linear como default"}',
 ARRAY['SITE_CREATION','TRAFFIC_MANAGEMENT','SOCIAL_MEDIA','FULL_DIGITAL'], ARRAY['CLOSER','QA'], true),
('Superpowers Workflow', 'superpowers-workflow', 'Spec-driven, brainstorming estruturado, TDD, verificação antes de completar.', 'prompt_template',
 '{"systemPromptAddition":"Ao executar projetos:\n- Spec-driven: documente antes de implementar\n- Proponha 2-3 abordagens antes de decidir\n- TDD: RED→GREEN→REFACTOR\n- Teste no app real antes de marcar concluído\n- Iterações pequenas: 10 commits pequenos > 1 grande\n- Post-mortem após cada entrega"}',
 ARRAY['SITE_CREATION','FULL_DIGITAL'], ARRAY['BUILDER','QA','BRIEFING'], true)
ON CONFLICT (slug) DO NOTHING;
